In [5]:
import numpy as np
import pandas as pd
from sympy import *
import math

In [6]:
x=Symbol('x')
def f(x):
    return diff(1/4*ln((x*x-1)/(x*x+1)))
f(x)

0.25*(x**2 + 1)*(-2*x*(x**2 - 1)/(x**2 + 1)**2 + 2*x/(x**2 + 1))/(x**2 - 1)

In [7]:
x=3
(0.25*(x*x+1)*(-1*(2*x*(x*x-1))/((x*x+1)*(x*x+1))+(2*x)/(x*x+1)))/(x*x-1)

0.0375

In [8]:
(pow(pow(5,2),pow(5,3))*pow(50,100))/(pow(100,50)*pow(pow(5,3),pow(5,2)))*pow(25,-137)

5.0

In [9]:
print(log(20, 225) * log(15, 289) * log(17, 20))

log(15)*log(17)/(log(225)*log(289))


In [10]:
math.log(15)*math.log(17)/(math.log(225)*math.log(289))


0.25

In [11]:
def f(x,y):
    return pow(x,3)+4*pow(y,3)-3*x-3*y
print(f(-1,0.5))
print(f(-1,-0.5))
print(f(1,0.5))
print(f(1,-0.5))

1.0
3.0
-3.0
-1.0


In [12]:
A = np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,1]])
B = np.array([[1,2,3],
              [5,6,7],
              [9,10,11],
              [4,8,12]])
C = np.array([[3,0,0],
              [0,3,0],
              [0,0,3]])
A = A * 2
D = np.dot(A,B)
np.dot(D,C)

array([[ 6, 12, 18],
       [30, 36, 42],
       [54, 60, 66],
       [24, 48, 72]])

In [13]:
A = np.array([[1,2,3],
              [5,6,7],
              [9,10,11],
              [4,8,12]])
B = np.array([[1],
              [5],
              [9]])
D = np.array([[3],
              [4],
              [1]])
C = np.array([1,2,3,4,5,6])
E1 = np.dot(A,B+D)
E2 = np.dot(A,B) + np.dot(A,D)
print(E1)
print(E2)

[[ 52]
 [144]
 [236]
 [208]]
[[ 52]
 [144]
 [236]
 [208]]


In [14]:
import numpy as np
mat = np.array([[2,1,0,0],[0,2,1,0],[0,0,2,1]])
print(mat)

[[2 1 0 0]
 [0 2 1 0]
 [0 0 2 1]]


In [15]:
mat.shape[0]*mat.shape[1]

12

In [16]:
mat.reshape(-1,1)

array([[2],
       [1],
       [0],
       [0],
       [0],
       [2],
       [1],
       [0],
       [0],
       [0],
       [2],
       [1]])

In [17]:
arr = ((0, -0.5), (1, 0), (0, 0.5), (0, 1.5), (1, 2.5), (2,3))

def sqerr(a, b):
  return (a - b)**2

def abserr(a, b):
  return abs(a - b)

def errsum(err_fun):
  return sum(list(map(lambda pair: err_fun(pair[0], pair[1]), arr)))

print(errsum(abserr))
print(errsum(sqerr))

6.0
7.0


In [19]:
arr = np.array([[10,60], [7,50], [12,75]])
arrX = arr[:,1]
print(arrX)
arrY = arr[:,0]
print(arrY)
fp1, residuals, rank, sv, rcond = np.polyfit(arrX, arrY, 1, full=True)

print(fp1)

[60 50 75]
[10  7 12]
[ 0.19473684 -2.34210526]


In [25]:
X = np.array([[1,60],[1,50],[1,75]])
y = np.array([[10],[7],[12]])
step1 = X.T.dot(X)
print(step1)
#step2 = linalg.inv(step1)
#step3 = step2.dot(X.T)
#b = step3.dot(y)

[[    3   185]
 [  185 11725]]
